name: Docker image

on:
  push:
    branches:
      - develop

env:
  REGISTRY: ghcr.io
  PROJECT_NAME: try-nest

jobs:
  build-push-image:
    name: Build and push image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Registry
        uses: ./.github/workflows/callables/registry
        with:
          token: ${{ secrets.IMAGE_TOKEN }}

      - name: Build / Push image
        uses: ./.github/workflows/callables/build-push
        with:
          context: .
          dockerfile: ./Dockerfile
          image: node
          target: prod
