name: Pipeline

on:
  push:
    branches:
      - develop
      - main
  pull_request:

jobs:
  pipeline-front:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Docker up
        run: make up node

      - name: Build
        run: make build

      - name: Linter
        run: make lint
